// Mirrors supabase/migrations/001_init.sql. Regenerate with:
// supabase gen types typescript --project-id <project-ref> > src/lib/supabase/database.types.ts
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Tables = {
  events: { Row: { id: string; slug: string; name: string; theme: string | null; scripture: string | null; start_date: string; end_date: string; venue: string | null; description: string | null; max_attendees: number | null; is_active: boolean; created_at: string }; Insert: Partial<Tables['events']['Row']> & Pick<Tables['events']['Row'], 'slug' | 'name' | 'start_date' | 'end_date'>; Update: Partial<Tables['events']['Row']> };
  list_items: { Row: { id: string; event_id: string; kind: 'band' | 'department' | 'church_group' | 'church_location'; name: string; is_active: boolean; sort_order: number; created_at: string }; Insert: Partial<Tables['list_items']['Row']> & Pick<Tables['list_items']['Row'], 'event_id' | 'kind' | 'name'>; Update: Partial<Tables['list_items']['Row']> };
  programmes: { Row: { id: string; event_id: string; title: string; description: string | null; day: string; start_time: string | null; end_time: string | null; location: string | null; is_active: boolean; sort_order: number }; Insert: Partial<Tables['programmes']['Row']> & Pick<Tables['programmes']['Row'], 'event_id' | 'title' | 'day'>; Update: Partial<Tables['programmes']['Row']> };
  activities: { Row: { id: string; event_id: string; name: string; description: string | null; group_requirement: string | null; starts_at: string | null; location: string | null; is_active: boolean }; Insert: Partial<Tables['activities']['Row']> & Pick<Tables['activities']['Row'], 'event_id' | 'name'>; Update: Partial<Tables['activities']['Row']> };
  members: { Row: { id: string; event_id: string; member_code: string; full_name: string; email: string; phone: string | null; gender: string | null; date_of_birth: string | null; address: string | null; occupation: string | null; emergency_contact: string | null; photo_path: string | null; band_id: string | null; church_location_id: string | null; church_group_id: string | null; source: 'home' | 'onsite'; is_first_timer: boolean; wants_permanent: boolean; convention_group: 'A' | 'B' | 'C' | 'D' | 'E'; biometric_status: string; status_token: string; consent_at: string | null; guardian_consent: boolean; client_created_at: string | null; created_at: string }; Insert: Partial<Tables['members']['Row']> & Pick<Tables['members']['Row'], 'id' | 'event_id' | 'member_code' | 'full_name' | 'email' | 'convention_group'>; Update: Partial<Tables['members']['Row']> };
  member_departments: { Row: { member_id: string; department_id: string }; Insert: Tables['member_departments']['Row']; Update: Partial<Tables['member_departments']['Row']> };
  executive_profiles: { Row: { member_id: string; user_id: string | null; leadership_role: string; approval: 'pending' | 'approved' | 'rejected'; approved_by: string | null; approved_at: string | null; exec_code: string; created_at: string }; Insert: Partial<Tables['executive_profiles']['Row']> & Pick<Tables['executive_profiles']['Row'], 'member_id' | 'leadership_role' | 'exec_code'>; Update: Partial<Tables['executive_profiles']['Row']> };
  registration_links: { Row: { id: string; event_id: string; kind: 'member' | 'executive'; token: string; created_by: string | null; expires_at: string | null; max_uses: number | null; uses: number; is_active: boolean; created_at: string }; Insert: Partial<Tables['registration_links']['Row']> & Pick<Tables['registration_links']['Row'], 'event_id' | 'kind'>; Update: Partial<Tables['registration_links']['Row']> };
  attendance: { Row: { id: string; event_id: string; member_id: string; checked_in_at: string; method: string; operator_id: string | null; device_id: string | null; client_event_id: string | null }; Insert: Partial<Tables['attendance']['Row']> & Pick<Tables['attendance']['Row'], 'event_id' | 'member_id' | 'method'>; Update: Partial<Tables['attendance']['Row']> };
  resource_claims: { Row: { id: string; event_id: string; member_id: string; resource: 'food' | 'souvenir'; slot: string; claimed_at: string; operator_id: string | null; device_id: string | null; client_event_id: string | null }; Insert: Partial<Tables['resource_claims']['Row']> & Pick<Tables['resource_claims']['Row'], 'event_id' | 'member_id' | 'resource'>; Update: Partial<Tables['resource_claims']['Row']> };
  activity_participation: { Row: { id: string; event_id: string; activity_id: string; member_id: string; recorded_by: string | null; recorded_at: string; client_event_id: string | null }; Insert: Partial<Tables['activity_participation']['Row']> & Pick<Tables['activity_participation']['Row'], 'event_id' | 'activity_id' | 'member_id'>; Update: Partial<Tables['activity_participation']['Row']> };
  convention_roles: { Row: { id: string; event_id: string; user_id: string; role: 'registration_desk' | 'verification_operator' | 'food_distributor' | 'souvenir_distributor' | 'activity_coordinator' | 'viewer'; assigned_by: string | null; assigned_at: string }; Insert: Partial<Tables['convention_roles']['Row']> & Pick<Tables['convention_roles']['Row'], 'event_id' | 'user_id' | 'role'>; Update: Partial<Tables['convention_roles']['Row']> };
  audit_log: { Row: { id: number; event_id: string | null; actor_id: string | null; action: string; target_type: string | null; target_id: string | null; details: Json | null; created_at: string }; Insert: Partial<Tables['audit_log']['Row']> & Pick<Tables['audit_log']['Row'], 'action'>; Update: Partial<Tables['audit_log']['Row']> };
};

export interface Database { public: { Tables: Tables; Views: Record<string, never>; Functions: { get_status_by_token: { Args: { p_token: string }; Returns: Json }; record_check_in: { Args: { p_event: string; p_member: string; p_method: string; p_device: string; p_client_event: string }; Returns: Json }; claim_resource: { Args: { p_event: string; p_member: string; p_resource: 'food' | 'souvenir'; p_slot: string; p_device: string; p_client_event: string }; Returns: Json }; record_participation: { Args: { p_event: string; p_activity: string; p_member: string; p_client_event: string }; Returns: Json } }; Enums: Record<string, string> } }
