import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Plus, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

type ListKind = 'band' | 'department' | 'church_group' | 'church_location';
const steps = ['Convention details', 'Fellowship bands', 'Departments', 'Groups and locations', 'Distribution slots', 'Review'];

function ListEditor({ title, values, onChange, optional }: { title: string; values: string[]; onChange: (values: string[]) => void; optional?: boolean }) {
  const [value, setValue] = useState('');
  return <div className="space-y-3"><p className="text-sm text-portal-label">{optional ? 'Optional. You can add these later.' : 'Add items now or edit them later in Convention Settings.'}</p><div className="flex gap-2"><input value={value} onChange={event => setValue(event.target.value)} className="portal-focus min-h-11 flex-1 rounded-2xl border border-portal-line bg-portal-surface px-3 text-sm text-portal-ink" placeholder={`Add ${title.toLowerCase()}`} /><button type="button" onClick={() => { const next = value.trim(); if (next && !values.some(item => item.toLowerCase() === next.toLowerCase())) { onChange([...values, next]); setValue(''); } }} className="grid h-11 w-11 place-items-center rounded-full bg-portal-accent text-portal-accent-ink"><Plus className="h-4 w-4" /></button></div>{values.map((item, index) => <div key={`${item}-${index}`} className="flex items-center gap-2 rounded-2xl border border-portal-line bg-portal-surface px-3 py-2"><input value={item} onChange={event => onChange(values.map((value, position) => position === index ? event.target.value : value))} className="min-w-0 flex-1 bg-transparent text-sm outline-none" /><button type="button" onClick={() => onChange(values.filter((_, position) => position !== index))} className="grid h-9 w-9 place-items-center text-red-500"><Trash2 className="h-4 w-4" /></button></div>)}</div>;
}

export function FirstRunSetup({ onFinished }: { onFinished: () => void }) {
  const [step, setStep] = useState(0); const [eventId, setEventId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [details, setDetails] = useState({ name: '', theme: '', scripture: '', start_date: '', end_date: '', venue: '', description: '', max_attendees: '' });
  const [bands, setBands] = useState<string[]>([]); const [departments, setDepartments] = useState<string[]>([]); const [groups, setGroups] = useState<string[]>([]); const [locations, setLocations] = useState<string[]>([]); const [slots, setSlots] = useState<string[]>([]);
  const canContinue = useMemo(() => step !== 0 || Boolean(details.name && details.start_date && details.end_date && details.venue), [details, step]);
  useEffect(() => { void (async () => { const { data } = await (supabase as any).from('events').select('*').eq('is_active', false).order('created_at').limit(1).maybeSingle(); if (!data) return; setEventId(data.id); setDetails({ name: data.name ?? '', theme: data.theme ?? '', scripture: data.scripture ?? '', start_date: data.start_date ?? '', end_date: data.end_date ?? '', venue: data.venue ?? '', description: data.description ?? '', max_attendees: String(data.max_attendees ?? '') }); setSlots(data.claim_slots ?? []); const { data: rows } = await (supabase as any).from('list_items').select('*').eq('event_id', data.id).order('sort_order'); const byKind = (kind: ListKind) => (rows ?? []).filter((row: { kind: string }) => row.kind === kind).map((row: { name: string }) => row.name); setBands(byKind('band')); setDepartments(byKind('department')); setGroups(byKind('church_group')); setLocations(byKind('church_location')); })(); }, []);
  const save = async (finish = false) => { if (!canContinue) return; setSaving(true); try { const slug = details.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `event-${crypto.randomUUID().slice(0, 8)}`; const payload = { id: eventId ?? crypto.randomUUID(), slug, ...details, max_attendees: Number(details.max_attendees) || null, claim_slots: slots, is_active: finish }; const { data, error } = await (supabase as any).from('events').upsert(payload).select().single(); if (error) throw error; setEventId(data.id); const lists: Array<[ListKind, string[]]> = [['band', bands], ['department', departments], ['church_group', groups], ['church_location', locations]]; await (supabase as any).from('list_items').delete().eq('event_id', data.id); const items = lists.flatMap(([kind, names]) => names.filter(Boolean).map((name, sort_order) => ({ event_id: data.id, kind, name: name.trim(), sort_order }))); if (items.length) { const { error: listError } = await (supabase as any).from('list_items').insert(items); if (listError) throw listError; } if (finish) onFinished(); else setStep(current => Math.min(current + 1, steps.length - 1)); } finally { setSaving(false); } };
  const content = step === 0 ? <div className="grid gap-4 sm:grid-cols-2">{([['name', 'Convention name'], ['theme', 'Theme'], ['scripture', 'Scripture'], ['start_date', 'Start date'], ['end_date', 'End date'], ['venue', 'Venue'], ['max_attendees', 'Maximum attendees']] as const).map(([field, label]) => <label key={field} className={field === 'name' || field === 'venue' ? 'sm:col-span-2' : ''}><span className="mb-2 block text-sm font-medium text-portal-ink">{label}{['name','start_date','end_date','venue'].includes(field) ? ' *' : ''}</span><input type={field.includes('date') ? 'date' : field === 'max_attendees' ? 'number' : 'text'} value={details[field]} onChange={event => setDetails({ ...details, [field]: event.target.value })} className="portal-focus min-h-11 w-full rounded-2xl border border-portal-line bg-portal-surface px-3 text-sm text-portal-ink" /></label>)}<label className="sm:col-span-2"><span className="mb-2 block text-sm font-medium text-portal-ink">Description</span><textarea value={details.description} onChange={event => setDetails({ ...details, description: event.target.value })} className="portal-focus min-h-24 w-full rounded-2xl border border-portal-line bg-portal-surface p-3 text-sm text-portal-ink" /></label></div> : step === 1 ? <><ListEditor title="Band" values={bands} onChange={setBands} /><p className="rounded-2xl bg-portal-surface p-4 text-sm text-portal-label">Members without a band are automatically assigned to Group E. With zero bands, everyone is assigned to Group E.</p></> : step === 2 ? <ListEditor title="Department" values={departments} onChange={setDepartments} /> : step === 3 ? <div className="grid gap-6 sm:grid-cols-2"><ListEditor title="Church group" values={groups} onChange={setGroups} optional /><ListEditor title="Church location" values={locations} onChange={setLocations} optional /></div> : step === 4 ? <ListEditor title="Distribution slot" values={slots} onChange={setSlots} optional /> : <div className="space-y-3 text-sm text-portal-label"><p><strong className="text-portal-ink">{details.name || 'Untitled convention'}</strong> will become the active convention.</p><p>{bands.length} bands, {departments.length} departments, and {slots.length} distribution slots will be created.</p><p>After setup, generate a member registration link from the dashboard.</p></div>;
  return <main className="portal-theme portal-canvas min-h-screen p-4 sm:p-8"><section className="mx-auto max-w-3xl py-8"><div className="mb-8 flex flex-wrap gap-2">{steps.map((label, index) => <span key={label} className={`rounded-full px-3 py-1 text-xs ${index === step ? 'bg-portal-dark text-white' : 'border border-portal-line text-portal-label'}`}>{index + 1}. {label}</span>)}</div><div className="portal-card rounded-[30px] p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-portal-label">First-run setup</p><h1 className="mt-2 text-3xl font-semibold text-portal-ink">{steps[step]}</h1><div className="mt-7">{content}</div><div className="mt-8 flex justify-between gap-3"><button type="button" disabled={step === 0 || saving} onClick={() => setStep(step - 1)} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-portal-line px-4 text-sm text-portal-ink disabled:opacity-40"><ArrowLeft className="h-4 w-4" /> Back</button><button type="button" disabled={!canContinue || saving} onClick={() => void save(step === steps.length - 1)} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-portal-dark px-5 text-sm font-medium text-white disabled:opacity-50">{saving ? 'Saving...' : step === steps.length - 1 ? 'Finish setup' : 'Save and continue'} <ArrowRight className="h-4 w-4" /></button></div></div></section></main>;
}
