import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Users, Shield, UserCheck, Activity, Link2, ShieldCheck, QrCode, Copy, Download, X } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { AdminLayout } from '@/components/AdminLayout';
import { StatCard } from '@/components/StatCard';
import { useAppData } from '@/contexts/AppDataContext';
import { useToast } from '@/contexts/ToastContext';
import { BAND_COLORS } from '@/types';

const biometricStatusLabel = (status?: string) => {
  if (status === 'verified_checked_in') return { label: 'Biometric Verified', className: 'status-badge-green' };
  if (status === 'fingerprint_enrolled') return { label: 'Fingerprint Enrolled', className: 'status-badge-blue' };
  if (status === 'duplicate_attempt') return { label: 'Duplicate Attempt Detected', className: 'status-badge-red' };
  return { label: 'Pending Biometric Verification', className: 'status-badge-amber' };
};

export function AdminDashboard() {
  const { members, executives, attendance, addGeneratedLink } = useAppData();
  const { addToast } = useToast();
  const navigate = useNavigate();
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [linkType, setLinkType] = useState<'member' | 'executive'>('member');
  const [generatedUrl, setGeneratedUrl] = useState('');
  const [showQR, setShowQR] = useState(false);
  const [activities, setActivities] = useState<Array<{ text: string; time: string; color: string }>>([
    { text: 'John Okafor checked in via biometric', time: '2 min ago', color: '#10B981' },
    { text: 'New member registered: Sarah Adebayo', time: '5 min ago', color: '#2563EB' },
    { text: 'Executive link generated by Admin', time: '12 min ago', color: '#F59E0B' },
    { text: 'First timer: David Nwosu wants permanent membership', time: '18 min ago', color: '#6C5CE7' },
    { text: 'Grace Eze marked present - Morning Session', time: '25 min ago', color: '#10B981' },
    { text: 'Group assignment updated for 5 members', time: '32 min ago', color: '#2563EB' },
    { text: 'Convention settings modified by Admin', time: '45 min ago', color: '#F59E0B' },
    { text: 'Attendance report exported to Excel', time: '1 hour ago', color: '#6C5CE7' },
  ]);

  const bandData = [
    { name: 'Peniel', value: members.filter(m => m.fellowshipBand === 'Peniel').length, color: BAND_COLORS.Peniel },
    { name: 'Judah', value: members.filter(m => m.fellowshipBand === 'Judah').length, color: BAND_COLORS.Judah },
    { name: 'Zion', value: members.filter(m => m.fellowshipBand === 'Zion').length, color: BAND_COLORS.Zion },
    { name: 'Ephraim', value: members.filter(m => m.fellowshipBand === 'Ephraim').length, color: BAND_COLORS.Ephraim },
    { name: 'None', value: members.filter(m => m.fellowshipBand === 'None').length, color: BAND_COLORS.None },
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      const newActivities = [
        'New member registered via QR code',
        'Biometric check-in successful',
        'Executive profile updated',
        'First timer follow-up completed',
        'Attendance verified manually',
      ];
      const randomActivity = newActivities[Math.floor(Math.random() * newActivities.length)];
      setActivities(prev => [
        { text: randomActivity, time: 'Just now', color: '#10B981' },
        ...prev.slice(0, 7),
      ]);
    }, 8000);
    return () => clearInterval(interval);
  }, []);

  const generateLink = (type: 'member' | 'executive') => {
    const token = Math.random().toString(36).substring(2, 15);
    const basePath = `${window.location.origin}${window.location.pathname}`;
    const url = `${basePath}#/register/${type}?token=${token}`;
    setGeneratedUrl(url);
    setLinkType(type);
    setShowLinkModal(true);
    setShowQR(false);
    addGeneratedLink({ type, url, token, uses: 0, status: 'active' });
  };

  const copyLink = () => {
    navigator.clipboard.writeText(generatedUrl);
    addToast({ type: 'success', title: 'Link copied to clipboard!' });
  };

  const generateQR = () => {
    setShowQR(true);
  };

  return (
    <AdminLayout>
      {/* Stats Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">
        <StatCard icon={Users} iconColor="#2563EB" iconBg="rgba(37,99,235,0.1)" label="Total Youth Members" value={members.length} trend="12%" trendUp delay={0} />
        <StatCard icon={Shield} iconColor="#6C5CE7" iconBg="rgba(108,92,231,0.1)" label="Total Executives" value={executives.length} trend="5%" trendUp delay={0.1} />
        <StatCard icon={UserCheck} iconColor="#10B981" iconBg="rgba(16,185,129,0.1)" label="Convention Attendees" value={attendance.length} trend="23%" trendUp delay={0.2} />
        <StatCard icon={Activity} iconColor="#F59E0B" iconBg="rgba(245,158,11,0.1)" label="Live Attendance" value={Math.floor(attendance.length * 0.6)} isLive delay={0.3} />
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-8">
        {[
          { icon: Link2, label: 'Generate Member Link', sub: 'For regular members', gradient: 'from-royal-500 to-blue-500', action: () => generateLink('member') },
          { icon: ShieldCheck, label: 'Generate Executive Link', sub: 'For youth leaders', gradient: 'from-purple-accent to-purple-light', action: () => generateLink('executive') },
          { icon: QrCode, label: 'Generate QR Code', sub: 'For onsite check-in', gradient: 'from-emerald-500 to-emerald-600', action: () => { generateLink('member'); setShowQR(true); } },
        ].map((item, i) => (
          <motion.button
            key={item.label}
            className={`relative overflow-hidden rounded-2xl p-6 h-[120px] flex flex-col items-center justify-center gap-3 bg-gradient-to-br ${item.gradient} text-white shadow-lg`}
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.34, 1.56, 0.64, 1], delay: 0.3 + i * 0.1 }}
            whileHover={{ y: -4, scale: 1.02, boxShadow: '0 16px 40px rgba(0,0,0,0.2)' }}
            whileTap={{ scale: 0.97 }}
            onClick={item.action}
          >
            <item.icon className="w-8 h-8" />
            <span className="font-semibold text-sm">{item.label}</span>
            <span className="text-xs opacity-70">{item.sub}</span>
          </motion.button>
        ))}
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {/* Recent Registrations */}
        <motion.div
          className="xl:col-span-2 rounded-[20px] p-6 backdrop-blur-glass border bg-white/70 dark:bg-slate-900/65 border-white/45 dark:border-white/[0.08]"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
        >
          <div className="flex items-center justify-between mb-6">
            <h3 className="font-display font-semibold text-lg text-slate-900 dark:text-white">Recent Registrations</h3>
            <button onClick={() => navigate('/admin/registrations')} className="text-sm text-blue-500 hover:underline font-medium">View All</button>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-slate-200 dark:border-white/[0.06]">
                  {['Name', 'Member ID', 'Band', 'Department(s)', 'Group', 'Registered', 'Verification'].map(h => (
                    <th key={h} className="text-left text-xs font-medium uppercase tracking-[0.04em] text-slate-400 pb-3 pr-4">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {members.slice(0, 8).map((member, i) => (
                  <motion.tr
                    key={member.id}
                    className="border-b border-slate-100 dark:border-white/[0.04] hover:bg-blue-500/[0.03] transition-colors"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.6 + i * 0.03 }}
                  >
                    <td className="py-3 pr-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-royal-500 to-purple-accent flex items-center justify-center text-white text-xs font-bold">
                          {member.fullName.split(' ').map(n => n[0]).join('').slice(0, 2)}
                        </div>
                        <span className="text-sm font-medium text-slate-900 dark:text-slate-100">{member.fullName}</span>
                      </div>
                    </td>
                    <td className="py-3 pr-4">
                      <span className="font-mono text-xs text-purple-accent bg-purple-accent/10 px-2 py-1 rounded-md">{member.id}</span>
                    </td>
                    <td className="py-3 pr-4">
                      <span className={`status-badge-${member.fellowshipBand.toLowerCase()} text-[10px]`}>{member.fellowshipBand}</span>
                    </td>
                    <td className="py-3 pr-4 text-xs text-slate-500">{member.departments.slice(0, 2).join(', ')}</td>
                    <td className="py-3 pr-4">
                      <span className={`status-badge-${member.conventionGroup.toLowerCase().replace(' ', '-')} text-[10px]`}>{member.conventionGroup}</span>
                    </td>
                    <td className="py-3 pr-4 text-xs text-slate-500">{new Date(member.registeredAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</td>
                    <td className="py-3">
                      <span className={`${biometricStatusLabel(member.biometricStatus).className} text-[10px]`}>{biometricStatusLabel(member.biometricStatus).label}</span>
                    </td>
                  </motion.tr>
                ))}
              </tbody>
            </table>
          </div>
        </motion.div>

        {/* Right Column */}
        <div className="space-y-6">
          {/* Live Activity */}
          <motion.div
            className="rounded-[20px] p-6 backdrop-blur-glass border bg-white/70 dark:bg-slate-900/65 border-white/45 dark:border-white/[0.08]"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
          >
            <div className="flex items-center gap-2 mb-4">
              <h3 className="font-display font-semibold text-lg text-slate-900 dark:text-white">Live Activity</h3>
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            </div>
            <div className="space-y-4 max-h-[280px] overflow-y-auto scrollbar-thin">
              {activities.map((activity, i) => (
                <motion.div
                  key={`${activity.text}-${i}`}
                  className="flex items-start gap-3"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.7 + i * 0.05 }}
                >
                  <span className="w-2 h-2 rounded-full mt-1.5 flex-shrink-0" style={{ background: activity.color }} />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-slate-700 dark:text-slate-300 truncate">{activity.text}</p>
                    <p className="text-xs text-slate-400 mt-0.5">{activity.time}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Fellowship Distribution */}
          <motion.div
            className="rounded-[20px] p-6 backdrop-blur-glass border bg-white/70 dark:bg-slate-900/65 border-white/45 dark:border-white/[0.08]"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, ease: [0.34, 1.56, 0.64, 1], delay: 0.7 }}
          >
            <h3 className="font-display font-semibold text-lg text-slate-900 dark:text-white mb-4">Fellowship Band Distribution</h3>
            <div className="h-[200px]">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={bandData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {bandData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      background: 'rgba(15, 23, 42, 0.9)',
                      border: '1px solid rgba(255,255,255,0.1)',
                      borderRadius: '12px',
                      color: '#fff',
                      fontSize: '12px',
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="flex flex-wrap gap-3 mt-2 justify-center">
              {bandData.map(band => (
                <div key={band.name} className="flex items-center gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ background: band.color }} />
                  <span className="text-xs text-slate-600 dark:text-slate-400">{band.name}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>

      {/* Link Generation Modal */}
      {showLinkModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowLinkModal(false)} />
          <motion.div
            className="relative glass-modal dark:glass-modal-dark p-8 max-w-md w-full"
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 0.4, ease: [0.34, 1.56, 0.64, 1] }}
          >
            <button onClick={() => setShowLinkModal(false)} className="absolute top-4 right-4 text-slate-400 hover:text-slate-600">
              <X className="w-5 h-5" />
            </button>
            <h3 className="font-display font-bold text-xl text-slate-900 dark:text-white mb-4">
              {linkType === 'member' ? 'Member' : 'Executive'} Registration Link
            </h3>
            <div className="flex items-center gap-2 p-3 rounded-xl bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/[0.06]">
              <input value={generatedUrl} readOnly className="flex-1 bg-transparent text-sm text-slate-700 dark:text-slate-300 outline-none" />
              <button onClick={copyLink} className="p-2 rounded-lg hover:bg-slate-200 dark:hover:bg-white/10 transition-colors">
                <Copy className="w-4 h-4 text-slate-500" />
              </button>
            </div>
            {!showQR ? (
              <button onClick={generateQR} className="mt-4 gradient-btn w-full h-11 flex items-center justify-center gap-2">
                <QrCode className="w-4 h-4" /> Generate QR Code
              </button>
            ) : (
              <motion.div
                className="mt-4 flex flex-col items-center"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
              >
                <div className="gradient-border-qr">
                  <div className="bg-white p-4 rounded-2xl">
                    <QRCodeSVG value={generatedUrl} size={200} />
                  </div>
                </div>
                <button className="mt-4 text-sm text-blue-500 hover:underline flex items-center gap-1">
                  <Download className="w-4 h-4" /> Download QR
                </button>
              </motion.div>
            )}
          </motion.div>
        </div>
      )}
    </AdminLayout>
  );
}
