import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ShieldAlert, Upload, LogIn } from 'lucide-react';
import { useAppData } from '@/contexts/AppDataContext';
import { addRegisteredAuthUser } from '@/contexts/AuthContext';
import { useToast } from '@/contexts/ToastContext';
import { BAND_LIST, DEPARTMENT_LIST, EXECUTIVE_ROLES } from '@/types';
import type { FellowshipBand, Department } from '@/types';

export function ExecutiveRegistration() {
  const navigate = useNavigate();
  const location = useLocation();
  const { addExecutive, validateGeneratedLink, recordGeneratedLinkUse } = useAppData();
  const { addToast } = useToast();
  const token = new URLSearchParams(location.search).get('token');
  const registrationLink = validateGeneratedLink('executive', token);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [newId, setNewId] = useState('');
  const [tempPassword, setTempPassword] = useState('');

  const [form, setForm] = useState({
    fullName: '',
    leadershipRole: '',
    department: '' as Department | '',
    fellowshipBand: '' as FellowshipBand | '',
    phoneNumber: '',
    email: '',
    address: '',
    profilePhoto: '',
  });

  const update = (field: string, value: string) => setForm(prev => ({ ...prev, [field]: value }));

  const handlePhotoChange = (file?: File) => {
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      addToast({ type: 'error', title: 'Please select an image file' });
      return;
    }

    const reader = new FileReader();
    reader.onload = () => update('profilePhoto', String(reader.result));
    reader.readAsDataURL(file);
  };

  const submit = async () => {
    if (!registrationLink) {
      addToast({ type: 'error', title: 'Invalid executive registration link' });
      return;
    }

    if (!form.fullName || !form.leadershipRole || !form.department || !form.fellowshipBand || !form.phoneNumber || !form.email || !form.address || !form.profilePhoto) {
      addToast({ type: 'error', title: 'Please fill in all required fields' });
      return;
    }

    setSubmitting(true);
    await new Promise(r => setTimeout(r, 1000));

    try {
      const exec = addExecutive({
        fullName: form.fullName.trim(),
        leadershipRole: form.leadershipRole,
        department: form.department as Department,
        fellowshipBand: form.fellowshipBand as FellowshipBand,
        phoneNumber: form.phoneNumber.trim(),
        email: form.email.trim(),
        address: form.address.trim(),
        profilePhoto: form.profilePhoto,
      });
      const password = `exec-${exec.id.slice(-4)}`;

      addRegisteredAuthUser({
        email: exec.email,
        password,
        user: { email: exec.email, name: exec.fullName, role: 'executive' },
      });
      recordGeneratedLinkUse(registrationLink.id);
      setNewId(exec.id);
      setTempPassword(password);
      setSuccess(true);
      addToast({ type: 'success', title: 'Executive registration complete!' });
    } catch (error) {
      addToast({ type: 'error', title: error instanceof Error ? error.message : 'Unable to complete registration' });
    } finally {
      setSubmitting(false);
    }
  };

  const inputClass = 'glass-input w-full';

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0B1426] via-[#1A2342] to-[#0B1426] flex items-center justify-center p-4 relative overflow-hidden">
      <motion.div
        className="w-full max-w-[520px] relative z-10"
        initial={{ opacity: 0, y: 40, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ duration: 0.7, ease: [0.34, 1.56, 0.64, 1] }}
      >
        <div
          className="rounded-3xl p-8 backdrop-blur-glass-lg border bg-white/90 border-white/50 dark:bg-slate-900/90 dark:border-white/[0.1]"
          style={{ boxShadow: '0 24px 80px rgba(0,0,0,0.3)' }}
        >
          {!registrationLink ? (
            <div className="text-center py-8">
              <div className="w-16 h-16 rounded-2xl bg-red-500/10 text-red-500 flex items-center justify-center mx-auto mb-5">
                <ShieldAlert className="w-8 h-8" />
              </div>
              <h2 className="font-display font-bold text-2xl text-slate-900 dark:text-white">Admin Link Required</h2>
              <p className="text-sm text-slate-500 dark:text-slate-400 mt-3">
                Executive registration is restricted to active links generated by an admin.
              </p>
              <button onClick={() => navigate('/login')} className="mt-6 gradient-btn px-6 py-2.5">
                Go to Login
              </button>
            </div>
          ) : !success ? (
            <>
              <div className="text-center mb-6">
                <h2 className="font-display font-bold text-2xl gradient-text">Executive Leadership Registration</h2>
                <p className="text-xs text-slate-500 mt-1">Mountain of Solution Youth Fellowship - Executive Portal</p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-2">
                  <label className="text-xs text-slate-500 mb-1 block">Full Name *</label>
                  <input className={inputClass} value={form.fullName} onChange={e => update('fullName', e.target.value)} placeholder="Full Name" />
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Leadership Role *</label>
                  <select className={inputClass} value={form.leadershipRole} onChange={e => update('leadershipRole', e.target.value)}>
                    <option value="">Select Role</option>
                    {EXECUTIVE_ROLES.map(r => <option key={r} value={r}>{r}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Department *</label>
                  <select className={inputClass} value={form.department} onChange={e => update('department', e.target.value)}>
                    <option value="">Select Department</option>
                    {DEPARTMENT_LIST.map(d => <option key={d} value={d}>{d}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Fellowship Band *</label>
                  <select className={inputClass} value={form.fellowshipBand} onChange={e => update('fellowshipBand', e.target.value)}>
                    <option value="">Select Band</option>
                    {BAND_LIST.map(b => <option key={b} value={b}>{b}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Phone Number *</label>
                  <input className={inputClass} value={form.phoneNumber} onChange={e => update('phoneNumber', e.target.value)} placeholder="+234..." />
                </div>
                <div className="sm:col-span-2">
                  <label className="text-xs text-slate-500 mb-1 block">Email *</label>
                  <input type="email" className={inputClass} value={form.email} onChange={e => update('email', e.target.value)} placeholder="email@example.com" />
                </div>
                <div className="sm:col-span-2">
                  <label className="text-xs text-slate-500 mb-1 block">Home Address *</label>
                  <textarea className={`${inputClass} min-h-[60px]`} value={form.address} onChange={e => update('address', e.target.value)} placeholder="Your address" />
                </div>
                <div className="sm:col-span-2">
                  <label className="text-xs text-slate-500 mb-1 block">Profile Photo *</label>
                  <label className="border-2 border-dashed border-slate-200 dark:border-white/10 rounded-2xl min-h-[140px] flex flex-col items-center justify-center gap-2 hover:border-purple-accent/50 transition-colors cursor-pointer overflow-hidden">
                    {form.profilePhoto ? (
                      <img src={form.profilePhoto} alt="Profile preview" className="w-24 h-24 rounded-full object-cover border-4 border-white/60 shadow-lg" />
                    ) : (
                      <>
                        <Upload className="w-8 h-8 text-slate-400" />
                        <p className="text-xs text-slate-500">Click to upload executive profile photo</p>
                      </>
                    )}
                    <input type="file" accept="image/*" className="sr-only" onChange={e => handlePhotoChange(e.target.files?.[0])} />
                  </label>
                </div>
              </div>

              <motion.button
                onClick={submit}
                disabled={submitting}
                className="w-full mt-6 h-12 rounded-2xl bg-gradient-to-r from-purple-accent to-purple-light text-white font-semibold shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 disabled:opacity-80"
                whileHover={{ y: -1 }}
                whileTap={{ scale: 0.97 }}
              >
                {submitting ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : 'Register as Executive'}
              </motion.button>
            </>
          ) : (
            <motion.div className="text-center py-6" initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }}>
              <div className="w-20 h-20 rounded-full bg-emerald-500/10 flex items-center justify-center mx-auto mb-5">
                <svg className="w-12 h-12 text-emerald-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <motion.path d="M5 13l4 4L19 7" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 0.6, delay: 0.3 }} strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <h3 className="font-display font-bold text-2xl text-emerald-500">Registration Complete!</h3>
              <div className="mt-4 inline-block font-mono font-bold text-lg text-purple-accent bg-purple-accent/10 px-6 py-3 rounded-xl">{newId}</div>
              <p className="text-sm text-slate-500 mt-3">Your Executive ID</p>
              <div className="mt-4 rounded-2xl bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 p-4 text-left">
                <p className="text-xs uppercase tracking-wider text-slate-400">Dashboard Access</p>
                <p className="text-sm text-slate-700 dark:text-slate-200 mt-2">Email: <span className="font-medium">{form.email.trim().toLowerCase()}</span></p>
                <p className="text-sm text-slate-700 dark:text-slate-200 mt-1">Temporary password: <span className="font-mono font-semibold">{tempPassword}</span></p>
              </div>
              <motion.button onClick={() => navigate('/login')} className="mt-6 gradient-btn flex items-center gap-2 px-6 py-2.5 mx-auto" whileTap={{ scale: 0.97 }}>
                <LogIn className="w-4 h-4" /> Go to Login
              </motion.button>
            </motion.div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
